# Generated by Django 5.2.3 on 2025-06-23 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('wait', '대기'), ('ing', '진행'), ('done', '완료')], default='wait', max_length=10),
        ),
    ]
